# Generated by Django 3.0.8 on 2020-07-27 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailPost',
            fields=[
                
                ('text', models.TextField(verbose_name='Текст')),
                ('timeSecond', models.IntegerField(blank=True, null=True, verbose_name='Кол-во секунд')),
                ('sent', models.BooleanField(default=False, verbose_name='Отправлено (да/нет)')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
        ),
    ]
