# Generated by Django 3.0.8 on 2020-07-28 05:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0002_auto_20200728_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailpost',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Уникальный ключ'),
        ),
    ]
